export const HOTS_MAPS = [
  { id: 'alterac-pass', name: 'Alterac Pass' },
  { id: 'battlefield-eternity', name: 'Battlefield Eternity' },
  { id: 'braxis-holdout', name: 'Braxis Holdout' },
  { id: 'cursed-hollow', name: 'Cursed Hollow' },
  { id: 'dragon-shire', name: 'Dragon Shire' },
  { id: 'garden-of-terror', name: 'Garden of Terror' },
  { id: 'hanamura-temple', name: 'Hanamura Temple' },
  { id: 'infernal-shrines', name: 'Infernal Shrines' },
  { id: 'sky-temple', name: 'Sky Temple' },
  { id: 'tomb-of-spider-queen', name: 'Tomb of the Spider Queen' },
  { id: 'towers-of-doom', name: 'Towers of Doom' },
  { id: 'volskaya-foundry', name: 'Volskaya Foundry' },
]

export const HERO_ROLES = [
  { id: 'TANK', label: 'Tank' },
  { id: 'BRUISER', label: 'Bruiser' },
  { id: 'RANGED_ASSASSIN', label: 'Ranged Assassin' },
  { id: 'MELEE_ASSASSIN', label: 'Melee Assassin' },
  { id: 'HEALER', label: 'Healer' },
  { id: 'SUPPORT', label: 'Support' },
]

export const HOTS_HEROES = [
  { id: 'abathur', name: 'Abathur', role: 'SUPPORT', roleLabel: 'Specialist', franchise: 'StarCraft', portrait: '/heroes/abathur_card_portrait.avif' },
  { id: 'alarak', name: 'Alarak', role: 'MELEE_ASSASSIN', roleLabel: 'Melee Assassin', franchise: 'StarCraft', portrait: '/heroes/alarak_card_portrait.webp' },
  { id: 'alexstrasza', name: 'Alexstrasza', role: 'HEALER', roleLabel: 'Healer', franchise: 'Warcraft', portrait: '/heroes/alexstrasza_card_portrait.avif' },
  { id: 'ana', name: 'Ana', role: 'HEALER', roleLabel: 'Healer', franchise: 'Overwatch', portrait: '/heroes/ana_card_portrait.avif' },
  { id: 'anduin', name: 'Anduin', role: 'HEALER', roleLabel: 'Healer', franchise: 'Warcraft', portrait: '/heroes/anduin_card_portrait.avif' },
  { id: 'anubarak', name: 'Anub\'arak', role: 'TANK', roleLabel: 'Tank', franchise: 'Warcraft', portrait: '/heroes/anubarak_card_portrait.avif' },
  { id: 'artanis', name: 'Artanis', role: 'BRUISER', roleLabel: 'Bruiser', franchise: 'StarCraft', portrait: '/heroes/artanis_card_portrait.avif' },
  { id: 'arthas', name: 'Arthas', role: 'TANK', roleLabel: 'Tank', franchise: 'Warcraft', portrait: '/heroes/arthas_card_portrait.avif' },
  { id: 'auriel', name: 'Auriel', role: 'HEALER', roleLabel: 'Healer', franchise: 'Diablo', portrait: '/heroes/auriel_card_portrait.webp' },
  { id: 'azmodan', name: 'Azmodan', role: 'RANGED_ASSASSIN', roleLabel: 'Ranged Assassin', franchise: 'Diablo', portrait: '/heroes/azmodan_card_portrait.avif' },
  { id: 'blaze', name: 'Blaze', role: 'BRUISER', roleLabel: 'Bruiser', franchise: 'StarCraft', portrait: '/heroes/blaze_card_portrait.avif' },
  { id: 'brightwing', name: 'Brightwing', role: 'HEALER', roleLabel: 'Healer', franchise: 'Warcraft', portrait: '/heroes/brightwing_card_portrait.webp' },
  { id: 'cassia', name: 'Cassia', role: 'RANGED_ASSASSIN', roleLabel: 'Ranged Assassin', franchise: 'Diablo', portrait: '/heroes/cassia_card_portrait.webp' },
  { id: 'chen', name: 'Chen', role: 'BRUISER', roleLabel: 'Bruiser', franchise: 'Warcraft', portrait: '/heroes/chen_card_portrait.avif' },
  { id: 'cho', name: 'Cho', role: 'TANK', roleLabel: 'Tank', franchise: 'Warcraft', portrait: '/heroes/cho_card_portrait.avif' },
  { id: 'chromie', name: 'Chromie', role: 'RANGED_ASSASSIN', roleLabel: 'Ranged Assassin', franchise: 'Warcraft', portrait: '/heroes/chromie_card_portrait.avif' },
  { id: 'dva', name: 'D.Va', role: 'BRUISER', roleLabel: 'Bruiser', franchise: 'Overwatch', portrait: '/heroes/dva_card_portrait.webp' },
  { id: 'deathwing', name: 'Deathwing', role: 'BRUISER', roleLabel: 'Bruiser', franchise: 'Warcraft', portrait: '/heroes/deathwing_card_portrait.webp' },
  { id: 'deckard', name: 'Deckard', role: 'HEALER', roleLabel: 'Healer', franchise: 'Diablo', portrait: '/heroes/deckard_card_portrait.avif' },
  { id: 'dehaka', name: 'Dehaka', role: 'BRUISER', roleLabel: 'Bruiser', franchise: 'StarCraft', portrait: '/heroes/dehaka_card_portrait.avif' },
  { id: 'diablo', name: 'Diablo', role: 'TANK', roleLabel: 'Tank', franchise: 'Diablo', portrait: '/heroes/diablo_card_portrait.webp' },
  { id: 'etc', name: 'E.T.C.', role: 'TANK', roleLabel: 'Tank', franchise: 'Warcraft', portrait: '/heroes/etc_card_portrait.avif' },
  { id: 'falstad', name: 'Falstad', role: 'RANGED_ASSASSIN', roleLabel: 'Ranged Assassin', franchise: 'Warcraft', portrait: '/heroes/falstad_card_portrait.avif' },
  { id: 'fenix', name: 'Fenix', role: 'RANGED_ASSASSIN', roleLabel: 'Ranged Assassin', franchise: 'StarCraft', portrait: '/heroes/fenix_card_portrait.avif' },
  { id: 'gall', name: 'Gall', role: 'RANGED_ASSASSIN', roleLabel: 'Ranged Assassin', franchise: 'Warcraft', portrait: '/heroes/gall_card_portrait.webp' },
  { id: 'garrosh', name: 'Garrosh', role: 'TANK', roleLabel: 'Tank', franchise: 'Warcraft', portrait: '/heroes/garrosh_card_portrait.avif' },
  { id: 'gazlowe', name: 'Gazlowe', role: 'BRUISER', roleLabel: 'Bruiser', franchise: 'Warcraft', portrait: '/heroes/gazlowe_card_portrait.webp' },
  { id: 'genji', name: 'Genji', role: 'RANGED_ASSASSIN', roleLabel: 'Ranged Assassin', franchise: 'Overwatch', portrait: '/heroes/genji_card_portrait.avif' },
  { id: 'greymane', name: 'Greymane', role: 'RANGED_ASSASSIN', roleLabel: 'Ranged Assassin', franchise: 'Warcraft', portrait: '/heroes/greymane_card_portrait.avif' },
  { id: 'guldan', name: 'Gul\'dan', role: 'RANGED_ASSASSIN', roleLabel: 'Ranged Assassin', franchise: 'Warcraft', portrait: '/heroes/guldan_card_portrait.avif' },
  { id: 'hanzo', name: 'Hanzo', role: 'RANGED_ASSASSIN', roleLabel: 'Ranged Assassin', franchise: 'Overwatch', portrait: '/heroes/hanzo_card_portrait.avif' },
  { id: 'hogger', name: 'Hogger', role: 'BRUISER', roleLabel: 'Bruiser', franchise: 'Warcraft', portrait: '/heroes/hogger_card_portrait.avif' },
  { id: 'illidan', name: 'Illidan', role: 'MELEE_ASSASSIN', roleLabel: 'Melee Assassin', franchise: 'Warcraft', portrait: '/heroes/illidan_card_portrait.webp' },
  { id: 'imperius', name: 'Imperius', role: 'BRUISER', roleLabel: 'Bruiser', franchise: 'Diablo', portrait: '/heroes/imperius_card_portrait.webp' },
  { id: 'jaina', name: 'Jaina', role: 'RANGED_ASSASSIN', roleLabel: 'Ranged Assassin', franchise: 'Warcraft', portrait: '/heroes/jaina_card_portrait.webp' },
  { id: 'johanna', name: 'Johanna', role: 'TANK', roleLabel: 'Tank', franchise: 'Diablo', portrait: '/heroes/johanna_card_portrait.webp' },
  { id: 'junkrat', name: 'Junkrat', role: 'RANGED_ASSASSIN', roleLabel: 'Ranged Assassin', franchise: 'Overwatch', portrait: '/heroes/junkrat_card_portrait.avif' },
  { id: 'kaelthas', name: 'Kael\'thas', role: 'RANGED_ASSASSIN', roleLabel: 'Ranged Assassin', franchise: 'Warcraft', portrait: '/heroes/kaelthas_card_portrait.webp' },
  { id: 'kelthuzad', name: 'Kel\'Thuzad', role: 'RANGED_ASSASSIN', roleLabel: 'Ranged Assassin', franchise: 'Warcraft', portrait: '/heroes/kelthuzad_card_portrait.webp' },
  { id: 'kerrigan', name: 'Kerrigan', role: 'MELEE_ASSASSIN', roleLabel: 'Melee Assassin', franchise: 'StarCraft', portrait: '/heroes/kerrigan_card_portrait.avif' },
  { id: 'kharazim', name: 'Kharazim', role: 'HEALER', roleLabel: 'Healer', franchise: 'Diablo', portrait: '/heroes/kharazim_card_portrait.avif' },
  { id: 'leoric', name: 'Leoric', role: 'BRUISER', roleLabel: 'Bruiser', franchise: 'Diablo', portrait: '/heroes/leoric_card_portrait.avif' },
  { id: 'li-li', name: 'Li Li', role: 'HEALER', roleLabel: 'Healer', franchise: 'Warcraft', portrait: '/heroes/lili_card_portrait.avif' },
  { id: 'li-ming', name: 'Li-Ming', role: 'RANGED_ASSASSIN', roleLabel: 'Ranged Assassin', franchise: 'Diablo', portrait: '/heroes/liming_card_portrait.webp' },
  { id: 'lt-morales', name: 'Lt. Morales', role: 'HEALER', roleLabel: 'Healer', franchise: 'StarCraft', portrait: '/heroes/ltmorales_card_portrait.webp' },
  { id: 'lucio', name: 'Lúcio', role: 'HEALER', roleLabel: 'Healer', franchise: 'Overwatch', portrait: '/heroes/lucio_card_portrait.avif' },
  { id: 'lunara', name: 'Lunara', role: 'RANGED_ASSASSIN', roleLabel: 'Ranged Assassin', franchise: 'Warcraft', portrait: '/heroes/lunara_card_portrait.avif' },
  { id: 'maiev', name: 'Maiev', role: 'MELEE_ASSASSIN', roleLabel: 'Melee Assassin', franchise: 'Warcraft', portrait: '/heroes/maiev_card_portrait.avif' },
  { id: 'malganis', name: 'Mal\'Ganis', role: 'TANK', roleLabel: 'Tank', franchise: 'Warcraft', portrait: '/heroes/malganis_card_portrait.avif' },
  { id: 'malfurion', name: 'Malfurion', role: 'HEALER', roleLabel: 'Healer', franchise: 'Warcraft', portrait: '/heroes/malfurion_card_portrait.avif' },
  { id: 'malthael', name: 'Malthael', role: 'BRUISER', roleLabel: 'Bruiser', franchise: 'Diablo', portrait: '/heroes/malthael_card_portrait.webp' },
  { id: 'medivh', name: 'Medivh', role: 'SUPPORT', roleLabel: 'Support', franchise: 'Warcraft', portrait: '/heroes/medivh_card_portrait.avif' },
  { id: 'mephisto', name: 'Mephisto', role: 'RANGED_ASSASSIN', roleLabel: 'Ranged Assassin', franchise: 'Diablo', portrait: '/heroes/mephisto_card_portrait.webp' },
  { id: 'mei', name: 'Mei', role: 'TANK', roleLabel: 'Tank', franchise: 'Overwatch', portrait: '/heroes/mei_card_portrait.avif' },
  { id: 'muradin', name: 'Muradin', role: 'TANK', roleLabel: 'Tank', franchise: 'Warcraft', portrait: '/heroes/muradin_card_portrait.avif' },
  { id: 'murky', name: 'Murky', role: 'MELEE_ASSASSIN', roleLabel: 'Melee Assassin', franchise: 'Warcraft', portrait: '/heroes/murky_card_portrait.avif' },
  { id: 'nazeebo', name: 'Nazeebo', role: 'RANGED_ASSASSIN', roleLabel: 'Ranged Assassin', franchise: 'Diablo', portrait: '/heroes/nazeebo_card_portrait.avif' },
  { id: 'nova', name: 'Nova', role: 'RANGED_ASSASSIN', roleLabel: 'Ranged Assassin', franchise: 'StarCraft', portrait: '/heroes/nova_card_portrait.avif' },
  { id: 'orphea', name: 'Orphea', role: 'RANGED_ASSASSIN', roleLabel: 'Ranged Assassin', franchise: 'Nexus', portrait: '/heroes/orphea_card_portrait.webp' },
  { id: 'probius', name: 'Probius', role: 'RANGED_ASSASSIN', roleLabel: 'Ranged Assassin', franchise: 'StarCraft', portrait: '/heroes/probius_card_portrait.avif' },
  { id: 'qhira', name: 'Qhira', role: 'MELEE_ASSASSIN', roleLabel: 'Melee Assassin', franchise: 'Nexus', portrait: '/heroes/qhira_card_portrait.webp' },
  { id: 'ragnaros', name: 'Ragnaros', role: 'BRUISER', roleLabel: 'Bruiser', franchise: 'Warcraft', portrait: '/heroes/ragnaros_card_portrait.webp' },
  { id: 'raynor', name: 'Raynor', role: 'RANGED_ASSASSIN', roleLabel: 'Ranged Assassin', franchise: 'StarCraft', portrait: '/heroes/raynor_card_portrait.webp' },
  { id: 'rehgar', name: 'Rehgar', role: 'HEALER', roleLabel: 'Healer', franchise: 'Warcraft', portrait: '/heroes/rehgar_card_portrait.avif' },
  { id: 'rexxar', name: 'Rexxar', role: 'BRUISER', roleLabel: 'Bruiser', franchise: 'Warcraft', portrait: '/heroes/rexxar_card_portrait.avif' },
  { id: 'samuro', name: 'Samuro', role: 'MELEE_ASSASSIN', roleLabel: 'Melee Assassin', franchise: 'Warcraft', portrait: '/heroes/samuro_card_portrait.avif' },
  { id: 'sgt-hammer', name: 'Sgt. Hammer', role: 'RANGED_ASSASSIN', roleLabel: 'Ranged Assassin', franchise: 'StarCraft', portrait: '/heroes/sgthammer_card_portrait.avif' },
  { id: 'sonya', name: 'Sonya', role: 'BRUISER', roleLabel: 'Bruiser', franchise: 'Diablo', portrait: '/heroes/sonya_card_portrait.avif' },
  { id: 'stitches', name: 'Stitches', role: 'TANK', roleLabel: 'Tank', franchise: 'Warcraft', portrait: '/heroes/stitches_card_portrait.avif' },
  { id: 'stukov', name: 'Stukov', role: 'HEALER', roleLabel: 'Healer', franchise: 'StarCraft', portrait: '/heroes/stukov_card_portrait.webp' },
  { id: 'sylvanas', name: 'Sylvanas', role: 'RANGED_ASSASSIN', roleLabel: 'Ranged Assassin', franchise: 'Warcraft', portrait: '/heroes/sylvanas_card_portrait.webp' },
  { id: 'tassadar', name: 'Tassadar', role: 'RANGED_ASSASSIN', roleLabel: 'Ranged Assassin', franchise: 'StarCraft', portrait: '/heroes/tassadar_card_portrait.avif' },
  { id: 'the-butcher', name: 'The Butcher', role: 'MELEE_ASSASSIN', roleLabel: 'Melee Assassin', franchise: 'Diablo', portrait: '/heroes/thebutcher_card_portrait.avif' },
  { id: 'the-lost-vikings', name: 'The Lost Vikings', role: 'SUPPORT', roleLabel: 'Support', franchise: 'Blizzard', portrait: '/heroes/thelostvikings_card_portrait.avif' },
  { id: 'thrall', name: 'Thrall', role: 'BRUISER', roleLabel: 'Bruiser', franchise: 'Warcraft', portrait: '/heroes/thrall_card_portrait.avif' },
  { id: 'tracer', name: 'Tracer', role: 'RANGED_ASSASSIN', roleLabel: 'Ranged Assassin', franchise: 'Overwatch', portrait: '/heroes/tracer_card_portrait.avif' },
  { id: 'tychus', name: 'Tychus', role: 'RANGED_ASSASSIN', roleLabel: 'Ranged Assassin', franchise: 'StarCraft', portrait: '/heroes/tychus_card_portrait.webp' },
  { id: 'tyrael', name: 'Tyrael', role: 'TANK', roleLabel: 'Tank', franchise: 'Diablo', portrait: '/heroes/tyrael_card_portrait.webp' },
  { id: 'tyrande', name: 'Tyrande', role: 'HEALER', roleLabel: 'Healer', franchise: 'Warcraft', portrait: '/heroes/tyrande_card_portrait.avif' },
  { id: 'uther', name: 'Uther', role: 'HEALER', roleLabel: 'Healer', franchise: 'Warcraft', portrait: '/heroes/uther_card_portrait.webp' },
  { id: 'valeera', name: 'Valeera', role: 'MELEE_ASSASSIN', roleLabel: 'Melee Assassin', franchise: 'Warcraft', portrait: '/heroes/valeera_card_portrait.avif' },
  { id: 'valla', name: 'Valla', role: 'RANGED_ASSASSIN', roleLabel: 'Ranged Assassin', franchise: 'Diablo', portrait: '/heroes/valla_card_portrait.avif' },
  { id: 'varian', name: 'Varian', role: 'BRUISER', roleLabel: 'Bruiser', franchise: 'Warcraft', portrait: '/heroes/varian_card_portrait.avif' },
  { id: 'whitemane', name: 'Whitemane', role: 'HEALER', roleLabel: 'Healer', franchise: 'Warcraft', portrait: '/heroes/whitemane_card_portrait.webp' },
  { id: 'xul', name: 'Xul', role: 'BRUISER', roleLabel: 'Bruiser', franchise: 'Diablo', portrait: '/heroes/xul_card_portrait.webp' },
  { id: 'yrel', name: 'Yrel', role: 'BRUISER', roleLabel: 'Bruiser', franchise: 'Warcraft', portrait: '/heroes/yrel_card_portrait.avif' },
  { id: 'zagara', name: 'Zagara', role: 'RANGED_ASSASSIN', roleLabel: 'Ranged Assassin', franchise: 'StarCraft', portrait: '/heroes/zagara_card_portrait.webp' },
  { id: 'zarya', name: 'Zarya', role: 'SUPPORT', roleLabel: 'Support', franchise: 'Overwatch', portrait: '/heroes/zarya_card_portrait.avif' },
  { id: 'zeratul', name: 'Zeratul', role: 'MELEE_ASSASSIN', roleLabel: 'Melee Assassin', franchise: 'StarCraft', portrait: '/heroes/zeratul_card_portrait.avif' },
  { id: 'zuljin', name: 'Zul\'jin', role: 'RANGED_ASSASSIN', roleLabel: 'Ranged Assassin', franchise: 'Warcraft', portrait: '/heroes/zuljin_card_portrait.avif' },
]

export const COUNTRY_OPTIONS = [
  { code: 'AR', name: 'Argentina', flag: '🇦🇷' },
  { code: 'BO', name: 'Bolivia', flag: '🇧🇴' },
  { code: 'BR', name: 'Brasil', flag: '🇧🇷' },
  { code: 'CL', name: 'Chile', flag: '🇨🇱' },
  { code: 'CO', name: 'Colombia', flag: '🇨🇴' },
  { code: 'CR', name: 'Costa Rica', flag: '🇨🇷' },
  { code: 'CU', name: 'Cuba', flag: '🇨🇺' },
  { code: 'DO', name: 'República Dominicana', flag: '🇩🇴' },
  { code: 'EC', name: 'Ecuador', flag: '🇪🇨' },
  { code: 'SV', name: 'El Salvador', flag: '🇸🇻' },
  { code: 'GT', name: 'Guatemala', flag: '🇬🇹' },
  { code: 'HN', name: 'Honduras', flag: '🇭🇳' },
  { code: 'MX', name: 'México', flag: '🇲🇽' },
  { code: 'NI', name: 'Nicaragua', flag: '🇳🇮' },
  { code: 'PA', name: 'Panamá', flag: '🇵🇦' },
  { code: 'PY', name: 'Paraguay', flag: '🇵🇾' },
  { code: 'PE', name: 'Perú', flag: '🇵🇪' },
  { code: 'PR', name: 'Puerto Rico', flag: '🇵🇷' },
  { code: 'ES', name: 'España', flag: '🇪🇸' },
  { code: 'US', name: 'Estados Unidos', flag: '🇺🇸' },
  { code: 'UY', name: 'Uruguay', flag: '🇺🇾' },
  { code: 'VE', name: 'Venezuela', flag: '🇻🇪' },
]

export const MAP_NAME_BY_ID = Object.fromEntries(
  HOTS_MAPS.map((map) => [map.id, map.name]),
)

export const MAP_ID_BY_NAME = Object.fromEntries(
  HOTS_MAPS.map((map) => [map.name, map.id]),
)

export const HERO_BY_ID = Object.fromEntries(
  HOTS_HEROES.map((hero) => [hero.id, hero]),
)

export const HERO_ID_BY_NAME = Object.fromEntries(
  HOTS_HEROES.map((hero) => [hero.name, hero.id]),
)

export const COUNTRY_BY_CODE = Object.fromEntries(
  COUNTRY_OPTIONS.map((country) => [country.code, country]),
)

export const isValidCountryCode = (code) => Boolean(code && COUNTRY_BY_CODE[code])

const shared = {
  HOTS_MAPS,
  MAP_NAME_BY_ID,
  MAP_ID_BY_NAME,
  HERO_ROLES,
  HOTS_HEROES,
  HERO_BY_ID,
  HERO_ID_BY_NAME,
  COUNTRY_OPTIONS,
  COUNTRY_BY_CODE,
  isValidCountryCode,
}

export default shared
